<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>../Zommi.Windows/app.manifest</ApplicationManifest>
    <ApplicationIcon>../Zommi.Flutter/windows/runner/resources/app_icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Zommi.Windows/Zommi.Windows.csproj" />
  </ItemGroup>
</Project>
